
SRCS = _printf.c\
		_dec.c\
		_formats.c\
		_putstr.c\
		_nbr.c\
		_putchar.c\
		_unsigned.c\
		_big.c\
		_hex2.c\
		_void.c\
		_hex.c\

NAME = libftprintf.a

CC = cc

RM = rm -f

CFLAGS = -Wall -Wextra -Werror

OBJS = ${SRCS:.c=.o}

%.o : %.c
			${CC} ${CFLAGS} -c $< -o $@

${NAME} : ${OBJS}
			ar rcs ${NAME} ${OBJS}
			
all : ${NAME}

clean :
		${RM} ${OBJS}

fclean : clean
			${RM} ${NAME}

re : fclean all

		
		